apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ksqldb-setup
spec:
  serviceName: ksqldb-setup
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb-setup
  template:
    metadata:
      labels:
        app: ksqldb-setup
    spec:
      containers:
        - name: ksqldb-setup
          image: gcr.io/devx-testing/ksqldb-setup
          env:
            - name: KSQLDB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: KSQLDB_ENDPOINT
                  name: ccloud-secret
            - name: KSQLDB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KSQLDB_USERNAME
                  name: ccloud-secret
            - name: KSQLDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KSQLDB_PASSWORD
                  name: ccloud-secret
          resources:
            requests:
              memory: 512Mi # 768Mi
              cpu: 500m # 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb-setup
spec:
  clusterIP: None
  