apiVersion: v1
kind: Secret
metadata:
  name: ccloud-secret
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: $KAFKA_BOOTSTRAP_SERVERS
  KAFKA_USERNAME: $KAFKA_USERNAME
  KAFKA_PASSWORD: $KAFKA_PASSWORD
  SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
  SCHEMA_REGISTRY_KEY: $SCHEMA_REGISTRY_KEY
  SCHEMA_REGISTRY_PASSWORD: $SCHEMA_REGISTRY_PASSWORD
  KSQLDB_ENDPOINT: $KSQLDB_ENDPOINT
  KSQLDB_USERNAME: $KSQLDB_USERNAME
  KSQLDB_PASSWORD: $KSQLDB_PASSWORD 
